/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : string,
  'dob' : string,
  'status' : string,
  'name' : string,
  'createdAt' : string,
  'cityStateZip' : string,
  'ssnLast4' : string,
  'reportText' : string,
  'address' : string,
  'phone' : string,
}
export interface ClientInput {
  'dob' : string,
  'status' : string,
  'name' : string,
  'createdAt' : string,
  'cityStateZip' : string,
  'ssnLast4' : string,
  'reportText' : string,
  'address' : string,
  'phone' : string,
}
export interface Letter {
  'id' : string,
  'status' : string,
  'title' : string,
  'clientId' : string,
  'createdAt' : string,
  'text' : string,
}
export interface LetterInput {
  'status' : string,
  'title' : string,
  'clientId' : string,
  'createdAt' : string,
  'text' : string,
}
export interface Note {
  'clientId' : string,
  'text' : string,
  'updatedAt' : string,
}
export interface _SERVICE {
  'createClient' : ActorMethod<[ClientInput], string>,
  'createLetter' : ActorMethod<[LetterInput], string>,
  'deleteClient' : ActorMethod<[string], boolean>,
  'deleteLetter' : ActorMethod<[string], boolean>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getLettersByClient' : ActorMethod<[string], Array<Letter>>,
  'getNoteByClient' : ActorMethod<[string], [] | [Note]>,
  'updateClient' : ActorMethod<[Client], boolean>,
  'updateLetter' : ActorMethod<[Letter], boolean>,
  'upsertNote' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];