/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LetterInput {
    status: string;
    title: string;
    clientId: string;
    createdAt: string;
    text: string;
}
export interface ClientInput {
    dob: string;
    status: string;
    name: string;
    createdAt: string;
    cityStateZip: string;
    ssnLast4: string;
    reportText: string;
    address: string;
    phone: string;
}
export interface Letter {
    id: string;
    status: string;
    title: string;
    clientId: string;
    createdAt: string;
    text: string;
}
export interface Client {
    id: string;
    dob: string;
    status: string;
    name: string;
    createdAt: string;
    cityStateZip: string;
    ssnLast4: string;
    reportText: string;
    address: string;
    phone: string;
}
export interface Note {
    clientId: string;
    text: string;
    updatedAt: string;
}
export interface backendInterface {
    createClient(input: ClientInput): Promise<string>;
    createLetter(input: LetterInput): Promise<string>;
    deleteClient(clientId: string): Promise<boolean>;
    deleteLetter(letterId: string): Promise<boolean>;
    getClients(): Promise<Array<Client>>;
    getLettersByClient(clientId: string): Promise<Array<Letter>>;
    getNoteByClient(clientId: string): Promise<Note | null>;
    updateClient(client: Client): Promise<boolean>;
    updateLetter(letter: Letter): Promise<boolean>;
    upsertNote(clientId: string, text: string, updatedAt: string): Promise<boolean>;
}
import type { Note as _Note } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createClient(arg0: ClientInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0);
            return result;
        }
    }
    async createLetter(arg0: LetterInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLetter(arg0);
            return result;
        }
    }
    async deleteClient(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteLetter(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLetter(arg0);
            return result;
        }
    }
    async getClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClients();
            return result;
        }
    }
    async getLettersByClient(arg0: string): Promise<Array<Letter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLettersByClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLettersByClient(arg0);
            return result;
        }
    }
    async getNoteByClient(arg0: string): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoteByClient(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoteByClient(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClient(arg0: Client): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0);
            return result;
        }
    }
    async updateLetter(arg0: Letter): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLetter(arg0);
            return result;
        }
    }
    async upsertNote(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertNote(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
